# Generated by Django 4.1.7 on 2023-02-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
