# Generated by Django 4.1.7 on 2023-02-16 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_app', '0002_alter_bug_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={'ordering': ['complete']},
        ),
        migrations.RenameField(
            model_name='bug',
            old_name='completed',
            new_name='complete',
        ),
    ]
