# Generated by Django 4.1.7 on 2023-02-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_app', '0005_alter_bug_options_remove_bug_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='complete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
