# Generated by Django 4.1.7 on 2023-02-17 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug_app', '0007_alter_bug_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={'ordering': ['-complete']},
        ),
    ]
