# Generated by Django 4.1.7 on 2023-03-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_app', '0008_alter_bug_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
